In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
path = './dataset/'
filename = 'acne0.jpg'
path += filename

In [3]:
im = cv2.imread(path)

In [4]:
im = cv2.resize(im, (500,500), interpolation= cv2.INTER_LINEAR)
    


In [5]:
cv2.imshow('image',im)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
im = cv2.blur(im,(4,4))

In [7]:
cv2.imshow('blurred',im)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)

In [9]:
cv2.imshow("Gray",im )
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
ret, bw_img = cv2.threshold(im, 128, 255, cv2.THRESH_BINARY)

In [11]:
cv2.imshow("Binary", bw_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Detecting acne by drawing contours around them**

In [12]:
contours, hierarchy = cv2.findContours(bw_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

In [13]:
contours_area = []
for con in contours:
    area = cv2.contourArea(con)
    if 0 < area < 100000:
        contours_area.append(con)

In [14]:
contours_circles = []
for con in contours_area:
    perimeter = cv2.arcLength(con, True)
    area = cv2.contourArea(con)
    if perimeter == 0:
        break
    circularity = 4*math.pi*(area/(perimeter*perimeter))
    if 0.5 < circularity < 2:
        contours_circles.append(con)

In [15]:
contours_circles

[array([[[116, 455]],
 
        [[116, 457]],
 
        [[117, 458]],
 
        [[118, 458]],
 
        [[118, 455]]], dtype=int32),
 array([[[ 68, 426]],
 
        [[ 67, 427]],
 
        [[ 65, 427]],
 
        [[ 64, 428]],
 
        [[ 63, 428]],
 
        [[ 63, 430]],
 
        [[ 66, 430]],
 
        [[ 67, 429]],
 
        [[ 68, 429]],
 
        [[ 69, 428]],
 
        [[ 70, 428]],
 
        [[ 71, 427]],
 
        [[ 71, 426]]], dtype=int32),
 array([[[ 27, 398]],
 
        [[ 27, 400]],
 
        [[ 31, 400]],
 
        [[ 32, 399]],
 
        [[ 31, 398]]], dtype=int32),
 array([[[ 66, 320]],
 
        [[ 66, 322]],
 
        [[ 67, 323]],
 
        [[ 67, 321]]], dtype=int32),
 array([[[ 71, 315]],
 
        [[ 70, 316]],
 
        [[ 71, 317]]], dtype=int32),
 array([[[ 57, 290]],
 
        [[ 56, 291]],
 
        [[ 55, 291]],
 
        [[ 55, 292]],
 
        [[ 56, 293]],
 
        [[ 57, 292]]], dtype=int32),
 array([[[ 68, 234]],
 
        [[ 68, 235]],
 
        [[

In [16]:
cv2.drawContours(im, contours_circles, -1, (0, 255, 0), 3)

array([[ 62,  62,  62, ..., 102, 102, 102],
       [ 62,  62,  62, ..., 102, 102, 102],
       [ 61,  61,  61, ..., 102, 102, 102],
       ...,
       [ 34,  34,  34, ..., 146, 146, 146],
       [ 34,  34,  34, ..., 147, 146, 146],
       [ 34,  34,  34, ..., 147, 147, 147]], dtype=uint8)

In [ ]:
cv2.imshow('Contours', im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
no = len(contours_circles)
no

57

In [19]:
if(no <= 5):
    print("Clear")
elif (no <= 10):
    print("Mild")
elif(no <= 50):
    print("Moderate")
elif (no <= 80):
    print("Severe")
else :
    print("Extreme")

Severe


**Detecting acne by Hough Transform**

In [20]:
circles = cv2.HoughCircles(im,cv2.HOUGH_GRADIENT,1,5,
                           param1=118,param2=8,minRadius=0,maxRadius=7)

In [21]:
circles = np.uint16(np.around(circles))

In [22]:
circles

array([[[308, 336,   6],
        [428, 474,   3],
        [ 56, 292,   3],
        [290, 232,   6],
        [ 84, 296,   4],
        [ 74, 160,   6],
        [ 78, 338,   6],
        [288, 158,   6],
        [276, 356,   4],
        [300, 420,   6],
        [118, 456,   4],
        [110, 396,   6],
        [230, 218,   6],
        [ 88, 362,   4],
        [412, 328,   4],
        [ 18, 458,   5],
        [ 66, 266,   4],
        [ 62, 206,   3],
        [292, 158,   4],
        [ 66, 322,   3],
        [166, 346,   5],
        [ 72, 196,   5],
        [ 14, 394,   4],
        [110, 380,   4],
        [ 28, 398,   3],
        [ 86, 202,   4],
        [102, 334,   5],
        [ 64, 430,   4],
        [100, 410,   4],
        [ 26, 462,   2],
        [ 86, 464,   2],
        [304, 250,   4],
        [290, 168,   3],
        [ 16, 390,   2],
        [ 58, 458,   2],
        [ 76, 460,   2],
        [290, 442,   4],
        [ 40, 394,   2],
        [ 46, 170,   2],
        [ 50, 406,   2],


In [23]:
circles.shape

(1, 63, 3)

In [24]:
for i in circles[0,:]:
    cv2.circle(im,(i[0],i[1]),i[2],(0,255,0),2)
    cv2.circle(im,(i[0],i[1]),2,(0,0,255),3)


In [25]:
cv2.imshow('detected circles',im)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [26]:
no = circles.shape[1]
no

63

In [27]:
if(no <= 5):
    print("Clear")
elif (no <= 10):
    print("Mild")
elif(no <= 50):
    print("Moderate")
elif (no <= 80):
    print("Severe")
else :
    print("Extreme")

Severe
